version: "3.9"
services:
  udsbroker:
    ports: 
      - "8000:8000"
    image: "aitzol/udsbroker:3.5"
    depends_on:
      - mysql
      - memcache
    volumes:
      - assets:/app/static
      - ./server/rsa_key:/app/rsa_key
  taskManager:
    image: "aitzol/udsbroker:3.5"
    command: "python manage.py taskManager --start --foreground"
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: uds
      MYSQL_USER: udsuser
      MYSQL_PASSWORD: udspassword
    volumes:
      - dbdata:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
  mysql-guacamole:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamoleuser
      MYSQL_PASSWORD: guacamolepassword
    security_opt:
      - seccomp:unconfined
  memcache:
    image: "memcached"
  guacd:
    image: "guacamole/guacd"
    ports:
      - "4822:4822"
  guacamole:
    image: "guacamole/guacamole"
    volumes:
      - ./guacamoletunnel:/guacamole_home
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /guacamole_home
      MYSQL_HOSTNAME: mysql-guacamole
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamoleuser
      MYSQL_PASSWORD: guacamolepassword 
    links:
      - guacd
    ports:
      - "8080:8080"
    
  webserver:
    image: caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - assets:/media
      - ./caddy/data:/data
      - ./caddy/config:/config
      - caddyconfig:/config
      - caddydata:/data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - udsbroker
  uds-tunnel-server:
    image: aitzol/uds-tunnel-server:3.5
    ports: 
      - "7777:7777"
    volumes:
      - ./uds-tunnel/udstunnel.conf:/etc/udstunnel.conf
volumes:
  dbdata:
  assets:
  caddyconfig:
  caddydata:
