version: "3.9"
services:
  udsbroker:
    ports: 
      - "8000:8000"
    image: "aitzol/udsbroker:0.3"
    command: /bin/bash /start.sh
    depends_on:
      - mysql
      - memcached
    volumes:
      - assets:/app/uds/static
  guacamole:
    image: "aitzol/uds-guacamole-tunnel:0.3"
    command: /bin/bash /run_services.sh
    ports: 
      - "10443:10443"
    volumes:
      - ./certs:/etc/certs
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: uds
      MYSQL_USER: udsuser
      MYSQL_PASSWORD: udspassword
    volumes:
      - dbdata:/var/lib/mysql
  memcached:
    image: "memcached"
  webserver:
    image: nginx
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/nginx.conf
      - assets:/media
      - ./certs:/etc/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - udsbroker
volumes:
  dbdata:
  assets:
