version: "3.9"
services:
  server:
    ports: 
      - "8000:8000"
    image: "aitzol/udsserver:0.2"
    command: gunicorn -b :8000 --env DJANGO_SETTINGS_MODULE=server.settings server.wsgi
    depends_on:
      - mysql
      - memcached
  guacamole:
    image: "aitzol/uds-guacamole-tunnel:0.1"
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: uds
      MYSQL_USER: udsuser
      MYSQL_PASSWORD: udspassword
    volumes:
      - dbdata:/var/lib/mysql
  memcached:
    image: "memcached"
volumes:
  dbdata: